### PR TITLE
got show_window=False working. the option uses a capital 'D'

### PR DESCRIPTION
**Pull request by valerierose**

### CODE REVIEW

**Comment by valerierose** [comment]
Second commit implements some new povray elements.

**Comment by Zulko** [comment]
I wonder if changing the display argument `-d` to `-D` will not break for some versions of POVRay and I don't have the time to test. @haldean do you have an opinion on this ?

**Comment by valerierose** [comment]
I'm using povray 3.7. Lowercase d did not work for me.

**Comment by haldean** [comment]
I had it working with a lowercase 'd' before, but the manpage for 3.7 only specifies capital 'D'. We could make it dependent on POVRay versions; I could do a little research on when the option changed. Unfortunately I don't have the box that I originally made my original patch on, so I don't know what version I was running at the time.

**Comment by haldean** [comment]
Looking at the revision history of the POVRay manpage makes it look like that option hasn't changed since mid-2013, which was the oldest revision in their git repo. I have no idea how this was working before, sorry! :+1: from me.

**Comment by Zulko** [comment]
Thanks @haldean for confirming, thanks @valerierose for the commit !

**Comment by Zulko** [comment]
@valerierose: if you have simple examples with the new POVRay objects you introduced, can you add these to the examples folder ?

**Comment by valerierose** [comment]
I do. But it would add a dependency: numpy-stl.

**Comment by valerierose** [comment]
Nevermind, I'll find a way to do it without numpy-stl

**Comment by valerierose** [comment]
Will do!

**Pull request merged**
